name: meditrack_app
description: "Android & iOS İlaç Takip ve Hatırlatıcı Uygulaması"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Yerel Depolama (Dil & Ayarlar Tercihi)
  shared_preferences: ^2.3.5

  # Firebase Servisleri
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1

  # Bildirimler & Kesin Zamanlı Alarm
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  flutter_timezone: ^3.0.1

  # Medya & Görsel
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # Yardımcı Paketler
  intl: ^0.20.1
  uuid: ^4.5.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
