import 'package:flutter/material.dart';

class AppLanguage {
  final String code;
  final String name;
  final String nativeName;
  final String flag;

  const AppLanguage({
    required this.code,
    required this.name,
    required this.nativeName,
    required this.flag,
  });
}

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('tr'));
  }

  static const List<AppLanguage> supportedLanguages = [
    AppLanguage(code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷'),
    AppLanguage(code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧'),
    AppLanguage(code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸'),
    AppLanguage(code: 'zh', name: 'Chinese', nativeName: '中文 (简体)', flag: '🇨🇳'),
    AppLanguage(code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵'),
    AppLanguage(code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦'),
    AppLanguage(code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷'),
  ];

  static const List<Locale> supportedLocales = [
    Locale('tr'),
    Locale('en'),
    Locale('es'),
    Locale('zh'),
    Locale('ja'),
    Locale('ar'),
    Locale('fr'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    // ----------------------------------------------------
    // TÜRKÇE (tr)
    // ----------------------------------------------------
    'tr': {
      'app_name': 'MediTrack',
      'app_tagline': 'İlaçlarınızı ve Sağlığınızı Güvenle Takip Edin',
      'login': 'Giriş Yap',
      'register': 'Kayıt Ol',
      'email': 'E-posta',
      'password': 'Şifre',
      'full_name': 'Ad Soyad',
      'phone_number': 'Telefon Numarası',
      'emergency_contact': 'Hasta Yakını Bilgileri (Acil Durum)',
      'relative_name': 'Yakının Adı Soyadı',
      'relative_phone': 'Yakının Telefon Numarası',
      'relative_banner_label': 'Acil Durum Yakını',
      'no_account': 'Hesabınız yok mu?',
      'have_account': 'Zaten hesabınız var mı?',
      'register_and_start': 'Kayıt Ol ve Başla',
      'create_account_title': 'Hesap Oluşturun',
      'create_account_desc': 'İlaçlarınızı düzenli takip etmek ve acil durumlarda yakınınızı bilgilendirmek için bilgilerinizi giriniz.',
      'personal_info': 'Kişisel Bilgiler',
      'hello': 'Merhaba',
      'user': 'Kullanıcı',
      'today_schedule': 'Bugünkü İlaç Programınız',
      'low_stock_warning': '{count} ilacınızın stoğu azalıyor ({names})',
      'registered_medicines': 'Kayıtlı İlaçlarınız',
      'no_medicines_yet': 'Henüz ilaç eklenmemiş.\n"+" butonuna basarak ilk ilacınızı ekleyin.',
      'add_medicine': 'İlaç Ekle',
      'new_medicine_title': 'Yeni İlaç Ekle',
      'medicine_name': 'İlaç Adı',
      'dosage_label': 'Doz (Adet)',
      'dosage_unit': 'Adet',
      'current_stock': 'Mevcut Stok',
      'reminder_time': 'Hatırlatma Saati',
      'change': 'Değiştir',
      'save_medicine_btn': 'İlacı Kaydet & Alarm Kur',
      'box_photo': 'Kutu Fotoğrafı',
      'box_photo_title': 'İlaç Kutusu Fotoğrafı',
      'take_camera': 'Kamera ile Çek',
      'choose_gallery': 'Galeriden Seç',
      'took_dose': 'İçtim ✅',
      'snooze_15': '15 dk Ertele ⏳',
      'dose_recorded_success': '{name} alındı olarak kaydedildi.',
      'medicine_saved_success': '{name} başarıyla kaydedildi!',
      'remaining_stock': 'Kalan Stok: {stock} adet',
      'dose': 'Doz',
      'select_language': 'Dil Seçimi',
      'language': 'Dil',
      'settings': 'Ayarlar',
      'logout': 'Çıkış Yap',
      'logout_confirm_title': 'Çıkış Yapılsın mı?',
      'logout_confirm_desc': 'Hesabınızdan çıkış yapmak istediğinize emin misiniz?',
      'cancel': 'İptal',
      'confirm': 'Onayla',
      'delete': 'Sil',
      'delete_medicine_confirm': 'Bu ilacı silmek istediğinize emin misiniz?',
      'photo_error': 'Fotoğraf seçilemedi: {error}',
      'login_error': 'Giriş yapılamadı.',
      'user_not_found': 'Kullanıcı bulunamadı.',
      'wrong_password': 'Hatalı şifre.',
      'weak_password': 'Şifre çok zayıf. En az 6 karakter giriniz.',
      'email_in_use': 'Bu e-posta adresi zaten kullanımda.',
      'invalid_email': 'Geçersiz e-posta formatı.',
      'generic_error': 'Bir hata oluştu: {error}',
      'field_required': 'Bu alan gereklidir.',
      'name_example': 'Örn: Ahmet Yılmaz',
      'med_name_example': 'Örn: Parol 500mg',
      'relative_example': 'Örn: Ayşe Yılmaz (Kızı)',
      'phone_example': '05XX XXX XX XX',
      'min_6_char': 'En az 6 karakter',
      'login_first': 'Lütfen önce giriş yapınız.',
      'rtl': 'false',
    },

    // ----------------------------------------------------
    // ENGLISH (en)
    // ----------------------------------------------------
    'en': {
      'app_name': 'MediTrack',
      'app_tagline': 'Track Your Medications & Health Securely',
      'login': 'Sign In',
      'register': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'emergency_contact': 'Emergency Contact Info',
      'relative_name': "Relative's Full Name",
      'relative_phone': "Relative's Phone Number",
      'relative_banner_label': 'Emergency Contact',
      'no_account': "Don't have an account?",
      'have_account': 'Already have an account?',
      'register_and_start': 'Sign Up & Get Started',
      'create_account_title': 'Create Account',
      'create_account_desc': 'Enter your information to track medications and alert your loved ones in case of emergency.',
      'personal_info': 'Personal Information',
      'hello': 'Hello',
      'user': 'User',
      'today_schedule': "Today's Medication Schedule",
      'low_stock_warning': 'Low stock for {count} medications ({names})',
      'registered_medicines': 'Your Medications',
      'no_medicines_yet': 'No medications added yet.\nTap "+" button to add your first medication.',
      'add_medicine': 'Add Medicine',
      'new_medicine_title': 'Add New Medicine',
      'medicine_name': 'Medicine Name',
      'dosage_label': 'Dosage (Pills)',
      'dosage_unit': 'Pill(s)',
      'current_stock': 'Current Stock',
      'reminder_time': 'Reminder Time',
      'change': 'Change',
      'save_medicine_btn': 'Save Medicine & Set Alarm',
      'box_photo': 'Box Photo',
      'box_photo_title': 'Medicine Package Photo',
      'take_camera': 'Take Photo with Camera',
      'choose_gallery': 'Choose from Gallery',
      'took_dose': 'Taken ✅',
      'snooze_15': 'Snooze 15 min ⏳',
      'dose_recorded_success': '{name} marked as taken.',
      'medicine_saved_success': '{name} successfully saved!',
      'remaining_stock': 'Remaining Stock: {stock} units',
      'dose': 'Dose',
      'select_language': 'Select Language',
      'language': 'Language',
      'settings': 'Settings',
      'logout': 'Sign Out',
      'logout_confirm_title': 'Sign Out?',
      'logout_confirm_desc': 'Are you sure you want to sign out of your account?',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'delete': 'Delete',
      'delete_medicine_confirm': 'Are you sure you want to delete this medication?',
      'photo_error': 'Failed to select photo: {error}',
      'login_error': 'Failed to sign in.',
      'user_not_found': 'User not found.',
      'wrong_password': 'Incorrect password.',
      'weak_password': 'Password too weak. Please enter at least 6 characters.',
      'email_in_use': 'This email is already in use.',
      'invalid_email': 'Invalid email format.',
      'generic_error': 'An error occurred: {error}',
      'field_required': 'This field is required.',
      'name_example': 'e.g. John Doe',
      'med_name_example': 'e.g. Paracetamol 500mg',
      'relative_example': 'e.g. Jane Doe (Daughter)',
      'phone_example': '+1 555 123 4567',
      'min_6_char': 'At least 6 characters',
      'login_first': 'Please sign in first.',
      'rtl': 'false',
    },

    // ----------------------------------------------------
    // SPANISH (es)
    // ----------------------------------------------------
    'es': {
      'app_name': 'MediTrack',
      'app_tagline': 'Rastree sus medicamentos y salud con seguridad',
      'login': 'Iniciar Sesión',
      'register': 'Registrarse',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'full_name': 'Nombre Completo',
      'phone_number': 'Número de Teléfono',
      'emergency_contact': 'Contacto de Emergencia',
      'relative_name': 'Nombre del Familiar',
      'relative_phone': 'Teléfono del Familiar',
      'relative_banner_label': 'Contacto de Emergencia',
      'no_account': '¿No tienes una cuenta?',
      'have_account': '¿Ya tienes una cuenta?',
      'register_and_start': 'Registrarse y Comenzar',
      'create_account_title': 'Crear Cuenta',
      'create_account_desc': 'Ingrese sus datos para organizar sus medicamentos y avisar a sus allegados en emergencias.',
      'personal_info': 'Información Personal',
      'hello': 'Hola',
      'user': 'Usuario',
      'today_schedule': 'Horario de Medicación de Hoy',
      'low_stock_warning': 'Stock bajo en {count} medicamentos ({names})',
      'registered_medicines': 'Tus Medicamentos',
      'no_medicines_yet': 'Aún no has añadido medicamentos.\nToca "+" para añadir tu primer medicamento.',
      'add_medicine': 'Añadir Medicamento',
      'new_medicine_title': 'Añadir Nuevo Medicamento',
      'medicine_name': 'Nombre del Medicamento',
      'dosage_label': 'Dosis (Unidades)',
      'dosage_unit': 'Unidad(es)',
      'current_stock': 'Stock Actual',
      'reminder_time': 'Hora del Recordatorio',
      'change': 'Cambiar',
      'save_medicine_btn': 'Guardar Medicamento y Alarma',
      'box_photo': 'Foto del Envase',
      'box_photo_title': 'Foto del Envase del Medicamento',
      'take_camera': 'Tomar Foto con Cámara',
      'choose_gallery': 'Elegir de Galería',
      'took_dose': 'Tomado ✅',
      'snooze_15': 'Posponer 15 min ⏳',
      'dose_recorded_success': '{name} marcado como tomado.',
      'medicine_saved_success': '¡{name} guardado correctamente!',
      'remaining_stock': 'Stock restante: {stock} unidades',
      'dose': 'Dosis',
      'select_language': 'Seleccionar Idioma',
      'language': 'Idioma',
      'settings': 'Ajustes',
      'logout': 'Cerrar Sesión',
      'logout_confirm_title': '¿Cerrar Sesión?',
      'logout_confirm_desc': '¿Estás seguro de que deseas salir de tu cuenta?',
      'cancel': 'Cancelar',
      'confirm': 'Confirmar',
      'delete': 'Eliminar',
      'delete_medicine_confirm': '¿Deseas eliminar este medicamento?',
      'photo_error': 'No se pudo seleccionar la foto: {error}',
      'login_error': 'Error al iniciar sesión.',
      'user_not_found': 'Usuario no encontrado.',
      'wrong_password': 'Contraseña incorrecta.',
      'weak_password': 'Contraseña muy débil (mínimo 6 caracteres).',
      'email_in_use': 'El correo ya está en uso.',
      'invalid_email': 'Formato de correo no válido.',
      'generic_error': 'Ocurrió un error: {error}',
      'field_required': 'Este campo es obligatorio.',
      'name_example': 'Ej: Carlos García',
      'med_name_example': 'Ej: Paracetamol 500mg',
      'relative_example': 'Ej: María García (Hija)',
      'phone_example': '+34 600 000 000',
      'min_6_char': 'Mínimo 6 caracteres',
      'login_first': 'Por favor, inicia sesión primero.',
      'rtl': 'false',
    },

    // ----------------------------------------------------
    // CHINESE (zh)
    // ----------------------------------------------------
    'zh': {
      'app_name': 'MediTrack',
      'app_tagline': '安全管理您的用药与健康',
      'login': '登录',
      'register': '注册',
      'email': '电子邮箱',
      'password': '密码',
      'full_name': '姓名',
      'phone_number': '电话号码',
      'emergency_contact': '紧急联系人信息',
      'relative_name': '紧急联系人姓名',
      'relative_phone': '紧急联系人电话',
      'relative_banner_label': '紧急联系人',
      'no_account': '还没有账号？',
      'have_account': '已有账号？',
      'register_and_start': '注册并开始使用',
      'create_account_title': '创建新账号',
      'create_account_desc': '填写信息以跟踪用药并在紧急情况下通知家属。',
      'personal_info': '个人信息',
      'hello': '您好',
      'user': '用户',
      'today_schedule': '今日服药计划',
      'low_stock_warning': '{count} 种药品库存偏低 ({names})',
      'registered_medicines': '已登记的药品',
      'no_medicines_yet': '暂未添加药品。\n点击下方“+”按钮添加您的第一种药品。',
      'add_medicine': '添加药品',
      'new_medicine_title': '添加新药品',
      'medicine_name': '药品名称',
      'dosage_label': '剂量 (片/粒)',
      'dosage_unit': '片',
      'current_stock': '当前库存',
      'reminder_time': '提醒时间',
      'change': '更改',
      'save_medicine_btn': '保存药品并设置提醒',
      'box_photo': '药盒照片',
      'box_photo_title': '药盒/包装照片',
      'take_camera': '拍照上传',
      'choose_gallery': '从相册选择',
      'took_dose': '已服用 ✅',
      'snooze_15': '推迟15分钟 ⏳',
      'dose_recorded_success': '已记录服用 {name}',
      'medicine_saved_success': '{name} 保存成功！',
      'remaining_stock': '剩余库存: {stock} 件',
      'dose': '剂量',
      'select_language': '选择语言',
      'language': '语言',
      'settings': '设置',
      'logout': '退出登录',
      'logout_confirm_title': '确认退出？',
      'logout_confirm_desc': '您确定要退出当前账号吗？',
      'cancel': '取消',
      'confirm': '确认',
      'delete': '删除',
      'delete_medicine_confirm': '确定要删除该药品吗？',
      'photo_error': '图片选择失败: {error}',
      'login_error': '登录失败。',
      'user_not_found': '未找到该用户。',
      'wrong_password': '密码错误。',
      'weak_password': '密码过弱，请至少输入6位字符。',
      'email_in_use': '该邮箱已被注册。',
      'invalid_email': '邮箱格式不正确。',
      'generic_error': '发生错误: {error}',
      'field_required': '此项为必填项。',
      'name_example': '例如：张伟',
      'med_name_example': '例如：布洛芬片 200mg',
      'relative_example': '例如：李丽 (女儿)',
      'phone_example': '138 0000 0000',
      'min_6_char': '至少6个字符',
      'login_first': '请先登录。',
      'rtl': 'false',
    },

    // ----------------------------------------------------
    // JAPANESE (ja)
    // ----------------------------------------------------
    'ja': {
      'app_name': 'MediTrack',
      'app_tagline': 'お薬と健康をしっかり安全に管理',
      'login': 'ログイン',
      'register': '新規登録',
      'email': 'メールアドレス',
      'password': 'パスワード',
      'full_name': '氏名',
      'phone_number': '電話番号',
      'emergency_contact': '緊急連絡先情報',
      'relative_name': '緊急連絡先の氏名',
      'relative_phone': '緊急連絡先の電話番号',
      'relative_banner_label': '緊急連絡先',
      'no_account': 'アカウントをお持ちでないですか？',
      'have_account': '既にアカウントをお持ちですか？',
      'register_and_start': '登録して始める',
      'create_account_title': 'アカウントを作成',
      'create_account_desc': '薬の服用管理や緊急時の家族への通知のため情報を入力してください。',
      'personal_info': '個人情報',
      'hello': 'こんにちは',
      'user': 'ユーザー',
      'today_schedule': '今日のお薬スケジュール',
      'low_stock_warning': '{count}件のお薬の残量が少なくなっています ({names})',
      'registered_medicines': '登録されたお薬',
      'no_medicines_yet': 'まだお薬が登録されていません。\n「+」ボタンを押してお薬を追加してください。',
      'add_medicine': 'お薬を追加',
      'new_medicine_title': '新しいお薬を追加',
      'medicine_name': 'お薬の名前',
      'dosage_label': '用量（錠数）',
      'dosage_unit': '錠',
      'current_stock': '現在の在庫数',
      'reminder_time': 'リマインダー時刻',
      'change': '変更',
      'save_medicine_btn': 'お薬を保存してアラーム設定',
      'box_photo': 'パッケージ写真',
      'box_photo_title': 'お薬のパッケージ写真',
      'take_camera': 'カメラで撮影',
      'choose_gallery': 'ギャラリーから選択',
      'took_dose': '服用完了 ✅',
      'snooze_15': '15分スヌーズ ⏳',
      'dose_recorded_success': '{name} の服用を記録しました。',
      'medicine_saved_success': '{name} を正常に保存しました！',
      'remaining_stock': '残り在庫: {stock} 錠',
      'dose': '用量',
      'select_language': '言語を選択',
      'language': '言語',
      'settings': '設定',
      'logout': 'ログアウト',
      'logout_confirm_title': 'ログアウトしますか？',
      'logout_confirm_desc': 'アカウントからログアウトしてもよろしいですか？',
      'cancel': 'キャンセル',
      'confirm': '確認',
      'delete': '削除',
      'delete_medicine_confirm': 'このお薬を削除してもよろしいですか？',
      'photo_error': '写真の取得に失敗しました: {error}',
      'login_error': 'ログインに失敗しました。',
      'user_not_found': 'ユーザーが見つかりません。',
      'wrong_password': 'パスワードが正しくありません。',
      'weak_password': 'パスワードが弱すぎます（6文字以上）。',
      'email_in_use': 'このメールアドレスは既に使用されています。',
      'invalid_email': '無効なメールアドレス形式です。',
      'generic_error': 'エラーが発生しました: {error}',
      'field_required': 'この項目は必須です。',
      'name_example': '例：山田 太郎',
      'med_name_example': '例：ロキソニン 60mg',
      'relative_example': '例：山田 花子 (長女)',
      'phone_example': '090-1234-5678',
      'min_6_char': '6文字以上',
      'login_first': '先にログインしてください。',
      'rtl': 'false',
    },

    // ----------------------------------------------------
    // ARABIC (ar) - RTL Support
    // ----------------------------------------------------
    'ar': {
      'app_name': 'ميدي تراك',
      'app_tagline': 'تتبع أدويتك وصحتك بأمان واطمئنان',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'full_name': 'الاسم الكامل',
      'phone_number': 'رقم الهاتف',
      'emergency_contact': 'معلومات قريب المريض (طوارئ)',
      'relative_name': 'اسم القريب الكامل',
      'relative_phone': 'رقم هاتف القريب',
      'relative_banner_label': 'جهة اتصال الطوارئ',
      'no_account': 'ليس لديك حساب؟',
      'have_account': 'لديك حساب بالفعل؟',
      'register_and_start': 'إنشاء حساب والبدء',
      'create_account_title': 'إنشاء حساب جديد',
      'create_account_desc': 'أدخل معلوماتك لتنظيم أدويتك والتنبيه في حالات الطوارئ.',
      'personal_info': 'المعلومات الشخصية',
      'hello': 'مرحباً',
      'user': 'المستخدم',
      'today_schedule': 'جدول أدويتك لليوم',
      'low_stock_warning': 'مخزون منخفض لـ {count} من الأدوية ({names})',
      'registered_medicines': 'أدويتك المسجلة',
      'no_medicines_yet': 'لم يتم إضافة أي أدوية بعد.\nاضغط على زر "+" لإضافة دوائك الأول.',
      'add_medicine': 'إضافة دواء',
      'new_medicine_title': 'إضافة دواء جديد',
      'medicine_name': 'اسم الدواء',
      'dosage_label': 'الجرعة (عدد الحبات)',
      'dosage_unit': 'حبة',
      'current_stock': 'المخزون الحالي',
      'reminder_time': 'وقت التذكير',
      'change': 'تغيير',
      'save_medicine_btn': 'حفظ الدواء وضبط المنبه',
      'box_photo': 'صورة العلبة',
      'box_photo_title': 'صورة علبة الدواء',
      'take_camera': 'التقاط بالكاميرا',
      'choose_gallery': 'اختيار من المعرض',
      'took_dose': 'تم التناول ✅',
      'snooze_15': 'تأجيل 15 دقيقة ⏳',
      'dose_recorded_success': 'تم تسجيل تناول {name} بنجاح.',
      'medicine_saved_success': 'تم حفظ {name} بنجاح!',
      'remaining_stock': 'المخزون المتبقي: {stock} حبة',
      'dose': 'الجرعة',
      'select_language': 'اختيار اللغة',
      'language': 'اللغة',
      'settings': 'الإعدادات',
      'logout': 'تسجيل الخروج',
      'logout_confirm_title': 'تسجيل الخروج؟',
      'logout_confirm_desc': 'هل أنت متأكد من رغبتك في تسجيل الخروج من حسابك؟',
      'cancel': 'إلغاء',
      'confirm': 'تأكيد',
      'delete': 'حذف',
      'delete_medicine_confirm': 'هل أنت متأكد من حذف هذا الدواء؟',
      'photo_error': 'فشل اختيار الصورة: {error}',
      'login_error': 'فشل تسجيل الدخول.',
      'user_not_found': 'المستخدم غير موجود.',
      'wrong_password': 'كلمة المرور غير صحيحة.',
      'weak_password': 'كلمة المرور ضعيفة (6 أحرف على الأقل).',
      'email_in_use': 'البريد الإلكتروني مستخدم بالفعل.',
      'invalid_email': 'صيغة البريد الإلكتروني غير صالحة.',
      'generic_error': 'حدث خطأ: {error}',
      'field_required': 'هذا الحقل مطلوب.',
      'name_example': 'مثال: محمد أحمد',
      'med_name_example': 'مثال: باراسيتامول 500 ملغ',
      'relative_example': 'مثال: فاطمة أحمد (ابنة)',
      'phone_example': '05X XXX XXXX',
      'min_6_char': '6 أحرف على الأقل',
      'login_first': 'يرجى تسجيل الدخول أولاً.',
      'rtl': 'true',
    },

    // ----------------------------------------------------
    // FRENCH (fr)
    // ----------------------------------------------------
    'fr': {
      'app_name': 'MediTrack',
      'app_tagline': 'Suivez vos médicaments et votre santé en toute sécurité',
      'login': 'Connexion',
      'register': 'Inscription',
      'email': 'E-mail',
      'password': 'Mot de passe',
      'full_name': 'Nom complet',
      'phone_number': 'Numéro de téléphone',
      'emergency_contact': 'Contact d’urgence (Proche)',
      'relative_name': 'Nom complet du proche',
      'relative_phone': 'Téléphone du proche',
      'relative_banner_label': 'Contact d’urgence',
      'no_account': 'Vous n’avez pas de compte ?',
      'have_account': 'Vous avez déjà un compte ?',
      'register_and_start': 'S’inscrire et commencer',
      'create_account_title': 'Créer un compte',
      'create_account_desc': 'Renseignez vos informations pour suivre vos traitements et prévenir vos proches en cas d’urgence.',
      'personal_info': 'Informations personnelles',
      'hello': 'Bonjour',
      'user': 'Utilisateur',
      'today_schedule': 'Programme de prise du jour',
      'low_stock_warning': 'Stock faible pour {count} médicament(s) ({names})',
      'registered_medicines': 'Vos Médicaments',
      'no_medicines_yet': 'Aucun médicament enregistré.\nAppuyez sur "+" pour ajouter votre premier traitement.',
      'add_medicine': 'Ajouter un médicament',
      'new_medicine_title': 'Ajouter un nouveau médicament',
      'medicine_name': 'Nom du médicament',
      'dosage_label': 'Posologie (Comprimés)',
      'dosage_unit': 'Comprimé(s)',
      'current_stock': 'Stock actuel',
      'reminder_time': 'Heure du rappel',
      'change': 'Modifier',
      'save_medicine_btn': 'Enregistrer le médicament & Alarme',
      'box_photo': 'Photo de la boîte',
      'box_photo_title': 'Photo de l’emballage du médicament',
      'take_camera': 'Prendre une photo',
      'choose_gallery': 'Choisir dans la galerie',
      'took_dose': 'Pris ✅',
      'snooze_15': 'Reporter de 15 min ⏳',
      'dose_recorded_success': '{name} enregistré comme pris.',
      'medicine_saved_success': '{name} enregistré avec succès !',
      'remaining_stock': 'Stock restant : {stock} unités',
      'dose': 'Dose',
      'select_language': 'Choisir la langue',
      'language': 'Langue',
      'settings': 'Paramètres',
      'logout': 'Se déconnecter',
      'logout_confirm_title': 'Se déconnecter ?',
      'logout_confirm_desc': 'Êtes-vous sûr de vouloir vous déconnecter ?',
      'cancel': 'Annuler',
      'confirm': 'Confirmer',
      'delete': 'Supprimer',
      'delete_medicine_confirm': 'Voulez-vous supprimer ce médicament ?',
      'photo_error': 'Impossible de sélectionner la photo : {error}',
      'login_error': 'Échec de la connexion.',
      'user_not_found': 'Utilisateur introuvable.',
      'wrong_password': 'Mot de passe incorrect.',
      'weak_password': 'Mot de passe trop court (au moins 6 caractères).',
      'email_in_use': 'Cette adresse e-mail est déjà utilisée.',
      'invalid_email': 'Format d’e-mail invalide.',
      'generic_error': 'Une erreur est survenue : {error}',
      'field_required': 'Ce champ est obligatoire.',
      'name_example': 'Ex : Jean Dupont',
      'med_name_example': 'Ex : Paracétamol 500mg',
      'relative_example': 'Ex : Marie Dupont (Fille)',
      'phone_example': '06 12 34 56 78',
      'min_6_char': 'Au moins 6 caractères',
      'login_first': 'Veuillez d’abord vous connecter.',
      'rtl': 'false',
    },
  };

  String translate(String key, {Map<String, String>? params}) {
    final langCode = locale.languageCode;
    final map = _localizedValues[langCode] ?? _localizedValues['tr']!;
    String value = map[key] ?? _localizedValues['tr']?[key] ?? key;

    if (params != null) {
      params.forEach((paramKey, paramVal) {
        value = value.replaceAll('{$paramKey}', paramVal);
      });
    }

    return value;
  }

  bool get isRTL => locale.languageCode == 'ar';
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['tr', 'en', 'es', 'zh', 'ja', 'ar', 'fr']
        .contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension LocalizationExtension on BuildContext {
  String tr(String key, {Map<String, String>? params}) {
    return AppLocalizations.of(this).translate(key, params: params);
  }

  bool get isRTL => AppLocalizations.of(this).isRTL;
}
